import type { ChecklistItem, Contact } from "./types";

export const CHECKLIST_ITEMS: ChecklistItem[] = [
  // Semana 1
  {
    id: "1",
    title: "Completar el formulario de datos personales en MyHR",
    description: "Ingresar a MyHR y completar el perfil con datos de contacto, dirección y documentación.",
    category: "administrativo",
    week: 1,
    completed: false,
    dueDay: 1,
  },
  {
    id: "2",
    title: "Solicitar acceso a MyTE (carga de horas)",
    description: "Enviar solicitud de acceso a través del portal de herramientas. El tiempo de aprobación es de 1-2 días hábiles.",
    category: "accesos",
    week: 1,
    completed: false,
    dueDay: 1,
  },
  {
    id: "3",
    title: "Completar el curso de Code of Business Ethics",
    description: "Curso obligatorio disponible en el portal de capacitaciones. Duración aproximada: 45 minutos.",
    category: "capacitaciones",
    week: 1,
    completed: false,
    dueDay: 3,
  },
  {
    id: "4",
    title: "Reunión de bienvenida con tu People Lead",
    description: "Coordinar fecha y horario con tu People Lead para la reunión de incorporación.",
    category: "equipo",
    week: 1,
    completed: false,
    dueDay: 2,
  },
  {
    id: "5",
    title: "Solicitar acceso a los repositorios del proyecto",
    description: "Pedirle al Tech Lead del proyecto que te agregue a los repos de GitHub/Azure DevOps.",
    category: "accesos",
    week: 1,
    completed: false,
    dueDay: 3,
  },
  {
    id: "6",
    title: "Configurar VPN corporativa",
    description: "Instalar y configurar el cliente de VPN siguiendo la guía de IT. Contactar a soporte si hay problemas.",
    category: "accesos",
    week: 1,
    completed: false,
    dueDay: 2,
  },
  // Semana 2
  {
    id: "7",
    title: "Completar el curso de Data Privacy & Security",
    description: "Capacitación obligatoria para todos los empleados de la torre de Data.",
    category: "capacitaciones",
    week: 2,
    completed: false,
    dueDay: 8,
  },
  {
    id: "8",
    title: "Cargar tus primeras horas en MyTE",
    description: "Registrar las horas trabajadas de la primera semana antes del cierre del viernes.",
    category: "administrativo",
    week: 2,
    completed: false,
    dueDay: 8,
  },
  {
    id: "9",
    title: "Presentarte con el equipo del proyecto",
    description: "Coordinar una sesión corta de presentación con el equipo completo del proyecto asignado.",
    category: "equipo",
    week: 2,
    completed: false,
    dueDay: 9,
  },
  {
    id: "10",
    title: "Solicitar acceso a las herramientas del proyecto",
    description: "Gestionar accesos a las herramientas específicas del proyecto (Jira, Confluence, ambientes de desarrollo).",
    category: "accesos",
    week: 2,
    completed: false,
    dueDay: 10,
  },
];

export const CONTACTS: Contact[] = [
  {
    id: "1",
    name: "María González",
    role: "People Lead",
    email: "maria.gonzalez@accenture.com",
    area: "Recursos Humanos",
  },
  {
    id: "2",
    name: "Carlos Ramírez",
    role: "Tech Lead — Data Tower",
    email: "carlos.ramirez@accenture.com",
    area: "Data & Analytics",
  },
  {
    id: "3",
    name: "Mesa de Ayuda IT",
    role: "Soporte técnico",
    email: "it.support@accenture.com",
    area: "IT",
  },
  {
    id: "4",
    name: "Laura Méndez",
    role: "Responsable de Capacitaciones",
    email: "laura.mendez@accenture.com",
    area: "Learning & Development",
  },
  {
    id: "5",
    name: "Diego Torres",
    role: "Responsable de Accesos",
    email: "diego.torres@accenture.com",
    area: "IT Security",
  },
];
